apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: orders-list-api
spec:
  functionContentType: plaintext
  runtime: nodejs8
  source: |
    module.exports = { main: function (event, context) {
        const {response, request: {headers}} = event.extensions;
        response.setHeader("Content-Type", "application/json");
        return `[{"orderid": "00000001", "description": "First sample order", "amount": "100.00", "user": "${headers.claimuserid}"},{"orderid": "00000002", "description": "Second sample order", "amount": "102.00", "user": "${headers.claimuserid}"},{"orderid": "00000003", "description": "Third sample order", "amount": "402.00", "user": "${headers.claimuserid}"}]`;
    } }
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: orders-list-api
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
        # - handler: jwt
        #   config:
        #     trusted_issuers:
        #       - https://<idp>
        #     jwks_urls:
        #       - https://<idp>/oauth2/certs
      methods:
        - GET
  service:
    host: orders-list-api
    name: orders-list-api
    port: 80
