apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: orders-list-api
spec:
  functionContentType: plaintext
  runtime: nodejs8
  source: |
    module.exports = { main: function (event, context) {
        const {response, request: {headers}} = event.extensions;
        response.setHeader("Content-Type", "application/json");
        return `[{"orderid": "00000001", "description": "First sample order", "amount": "100.00", "user": "${headers.claimuserid}"},{"orderid": "00000002", "description": "Second sample order", "amount": "102.00", "user": "${headers.claimuserid}"},{"orderid": "00000003", "description": "Third sample order", "amount": "402.00", "user": "${headers.claimuserid}"}]`;
    } }
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: orders-list-api
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
  service:
    #host property to be removed... https://github.com/kyma-incubator/api-gateway/pull/95
    host: orders-list-api.c-65dd678.kyma-dev.shoot.canary.k8s-hana.ondemand.com
    name: orders-list-api
    port: 80
